### ISSUE TITLE
Really Great Work - base64 question

### ISSUE THREAD

**Issue by lassos** [prohetamine/mermaid-extension#1]
Really Great Work

wow wow wow

i really love it

in combination with my ahk (autohotkey) i can really do everything now getting direct messages via tcp/ip on port x

one question . i get the data on port, i a decode base64 i only get numbers comma separeted

i expected the plain text

""isParsedEvent":true,"parseEvent":{"isModel" :true,"isUser":false,"isAnon":false,"isNotice":false,"isToken":false,"isRemovedMessage":false,"isDisconnect":false,"isConnect": false,"isRoomCount":false,"tokenCount":0,"message":"MzQsMTAwLDExNSwxMDIsMTE1LDEwMiwxMDAsMzQ="

for example MzQsMTAwLDExNSwxMDIsMTE1LDEwMiwxMDAsMzQ= gives me only -> 34,100,115,102,115,102,100,34

**Comment by lassos** [comment]
Ok found it in lib -> charCodeAt -> so it also has to be decoded  -> String.fromCharCode

**Comment by lassos** [comment]
But why are thousands of messages sent to the port ?

**Comment by prohetamine** [comment]
Good afternoon, it's great that you like it. The fact is that I am currently developing a new system, the extension will receive some changes, and a full-fledged desktop application will appear in which there will be many new features, including for the developer, follow the news in telegram: https://t.me /+8VhIbWf_guE0ZDQy
